version: '3.8'
services:

  postgres-container:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ioana
      POSTGRES_DB: eVoteCollection
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kafka-container:
    image: bitnami/kafka:3.4
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ENABLE_KRAFT: "no"
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  zookeeper:
    image: bitnami/zookeeper:3.8
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  mongo-container:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  invite-cmd:
    image: priut/invite-cmd:latest
    restart: always
    ports:
      - 5004:5004
    depends_on:
      - kafka-container
      - mongo-container
      - user-query
      - votingevent-query
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  invite-query:
    image: priut/invite-query:latest
    restart: always
    ports:
      - 5005:5005
    depends_on:
      - kafka-container
      - postgres-container
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-cmd:
    image: priut/user-cmd:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - kafka-container
      - mongo-container
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  user-query:
    image: priut/user-query:latest
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - kafka-container
      - postgres-container
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  votingevent-cmd:
    image: priut/votingevent-cmd:latest
    restart: always
    ports:
      - 5002:5002
    depends_on:
      - kafka-container
      - mongo-container
      - invite-cmd
      - invite-query
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  votingevent-query:
    image: priut/votingevent-query:latest
    restart: always
    ports:
      - 5003:5003
    depends_on:
      - kafka-container
      - postgres-container
    networks:
      - eVote-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  eVote-network:
    external: true

volumes:
  mongodb_data_container:
  postgres_data:
  zookeeper_data:
  kafka_data:
