server:
  port: 5004
spring:
  data:
    mongodb:
      host: mongo-container
      #host: localhost
      port: 27017
      database: vote
  kafka:
    producer:
      bootstrap-servers: kafka-container:9092
      #bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer